name: Builder
on:
  push:
    branches: 
    - main
    - fishnet

  workflow_dispatch:

jobs:
  buildAll:
    name: Build ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - OSX
          - Windows64
          - Linux64
    steps:
      - name: Download Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Check Cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-      
      - name: Build Project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          buildName: LootyShooty-${{ matrix.targetPlatform }}
          buildsPath: build
          targetPlatform: Standalone${{ matrix.targetPlatform }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: LootyShooty-${{ matrix.targetPlatform }}
          path: build
  
  buildServer:
    name: Build Server Linux64
    runs-on: ubuntu-latest
    steps:
      - name: Download Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Check Cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-Server-StandaloneLinux64
          restore-keys: Library-Server-
      - name: Build Project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          customParameters: -EnableHeadlessMode
          buildName: LootyShooty-Server-Linux64
          buildsPath: build
          targetPlatform: StandaloneLinux64
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: LootyShooty-Server-Linux64
          path: build
