name: Builder
on:
  push:
    branches:
    - main
    - fishnet

  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.artifactName }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - targetPlatform: StandaloneWindows64
            artifactName: LootyShooty-Windows64
            os: windows-latest
            uploadPath: build/LootyShooty-Windows64
          - targetPlatform: StandaloneOSX
            artifactName: LootyShooty-OSX
            os: macos-latest
            uploadPath: build/LootyShooty-OSX.zip
          - targetPlatform: StandaloneLinux64
            artifactName: LootyShooty-Linux64
            os: ubuntu-latest
            uploadPath: build/LootyShooty-Linux64
          - targetPlatform: StandaloneLinux64
            artifactName: LootyShooty-Server-Linux64
            os: ubuntu-latest
            uploadPath: build/LootyShooty-Server-Linux64
            extraArgs: -standaloneBuildSubtarget Server
            modules: linux-server
    steps:
      - name: Download Repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ matrix.artifactName }}-${{ hashFiles('Packages/packages-lock.json') }}
          restore-keys: |
            Library-${{ matrix.artifactName }}-
            Library-

      - name: Install Unity
        uses: buildalon/unity-setup@v2
        with:
          version-file: ProjectSettings/ProjectVersion.txt
          build-targets: ${{ matrix.targetPlatform }}
          modules: ${{ matrix.modules }}

      - name: Activate Unity License
        uses: buildalon/activate-unity-license@v2
        with:
          license: 'Personal'
          username: ${{ secrets.UNITY_EMAIL }}
          password: ${{ secrets.UNITY_PASSWORD }}

      - name: Build Project
        uses: buildalon/unity-action@v3
        with:
          log-name: ${{ matrix.artifactName }}
          build-target: ${{ matrix.targetPlatform }}
          args: -quit -batchmode -executeMethod CIBuild.Build -buildPath build/${{ matrix.artifactName }} -buildName ${{ matrix.artifactName }} ${{ matrix.extraArgs }}

      - name: Package macOS App
        if: matrix.targetPlatform == 'StandaloneOSX'
        run: ditto -c -k --sequesterRsrc --keepParent "build/${{ matrix.artifactName }}/${{ matrix.artifactName }}.app" "${{ matrix.uploadPath }}"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifactName }}
          path: ${{ matrix.uploadPath }}
          if-no-files-found: error
